name: CI (Docs-Only)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ "*" ]

jobs:
  markdown:
    name: Markdown Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install markdownlint-cli2
        run: npm i -g markdownlint-cli2
      - name: Lint Markdown
        run: |
          markdownlint-cli2 "**/*.md" "#node_modules" "#.git" "#**/CHANGELOG*.md" \
            --config .markdownlint.jsonc

  links:
    name: Link Check (lychee)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lychee Link Checker
        uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --config .lychee.toml
            --no-progress
            --accept 200,206,429
            --exclude-loopback
            --max-concurrency 8
            .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  yaml_json:
    name: YAML/JSON Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq yamllint
      - name: Lint YAML
        run: |
          if ls **/*.y?(a)ml >/dev/null 2>&1; then
            yamllint -c .yamllint.yml .
          else
            echo "No YAML files found."
          fi
      - name: Lint JSON
        run: |
          set -e
          found=0
          while IFS= read -r -d '' f; do
            found=1
            jq empty "$f"
          done < <(git ls-files '*.json' -z)
          if [ "$found" -eq 0 ]; then
            echo "No JSON files found."
          fi

  meta:
    name: Repo Meta (Budget/License)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check budget stub
        run: |
          test -f ci/budget.json || (echo "ci/budget.json missing"; exit 1)
          jq -e '.budgets // {}' ci/budget.json >/dev/null
      - name: License check (non-blocking)
        continue-on-error: true
        run: |
          if [ ! -f LICENSE ]; then
            echo "LICENSE missing (non-blocking)"; exit 0
          fi
          head -n 1 LICENSE | grep -qi "license" || true
