name: security
on:
  pull_request:
    paths:
      - "apps/api/**"
      - "Cargo.*"
      - "deny.toml"
      - ".github/workflows/security.yml"
jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anchore/sbom-action@v0.15.7
        with:
          output-file: sbom.spdx.json
      - uses: actions/upload-artifact@v4
        with:
          name: weltgewebe-sbom-spdx
          path: sbom.spdx.json
