name: security
on:
  pull_request:
    paths:
      - "apps/api/**"
      - "Cargo.*"
      - "deny.toml"
      - ".github/workflows/security.yml"
jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install syft
        env:
          SYFT_BIN_DIR: ${{ runner.temp }}/syft
        run: |
          set -euo pipefail
          mkdir -p "$SYFT_BIN_DIR"
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | \
            sh -s -- -b "$SYFT_BIN_DIR"
      - uses: anchore/sbom-action@v0.15.7
        with:
          syft-path: ${{ runner.temp }}/syft/syft
          output-file: sbom.spdx.json
      - uses: actions/upload-artifact@v4
        with:
          name: weltgewebe-sbom-spdx-json
          path: sbom.spdx.json
