name: security
on:
  pull_request:
    paths:
      - "apps/api/**"
      - "Cargo.*"
      - "deny.toml"
      - ".github/workflows/security.yml"
jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EmbarkStudios/cargo-deny-action@v2
  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install syft
        env:
          SYFT_BIN_DIR: ${{ runner.temp }}/syft
        run: |
          set -euo pipefail
          mkdir -p "$SYFT_BIN_DIR"
          SYFT_VERSION="v0.102.0"
          SYFT_TARBALL="syft_${SYFT_VERSION#v}_linux_amd64.tar.gz"
          curl -sSfL -o "$SYFT_BIN_DIR/$SYFT_TARBALL" "https://github.com/anchore/syft/releases/download/${SYFT_VERSION}/${SYFT_TARBALL}"
          tar -xzf "$SYFT_BIN_DIR/$SYFT_TARBALL" -C "$SYFT_BIN_DIR"
          rm "$SYFT_BIN_DIR/$SYFT_TARBALL"
          chmod +x "$SYFT_BIN_DIR/syft"
      - uses: anchore/sbom-action@v0.15.7
        with:
          syft-path: ${{ runner.temp }}/syft/syft
          output-file: sbom.spdx.json
      - uses: actions/upload-artifact@v4
        with:
          name: weltgewebe_sbom_spdx_json
          path: sbom.spdx.json
