name: seo-archive
on:
  pull_request:
    paths:
      - "apps/web/**"
      - "docs/**"
      - ".github/workflows/seo-archive.yml"
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate archive routes (static hints)
        run: |
          grep -R "rel=\"canonical\"" -n apps/web || echo "::warning::no canonicals found"
          grep -R "/archive/" -n apps/web || echo "::warning::no archive routes"
