name: Web Check (Gate A)

permissions:
  contents: read

on:
  pull_request:
    branches: [main, dev]
    paths:
      - apps/web/**
      - .github/workflows/web.yml
  push:
    branches: [main, dev, 'feat/**', 'fix/**']
    paths:
      - apps/web/**
      - .github/workflows/web.yml

jobs:
  build:
    name: Build & Lint
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    defaults:
      run:
        working-directory: apps/web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: apps/web/pnpm-lock.yaml

      - name: Setup PNPM
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Determine pnpm store
        id: pnpm-store
        run: echo "store=$(pnpm store path --silent)" >> "$GITHUB_OUTPUT"

      - name: Cache pnpm store
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-store.outputs.store }}
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: pnpm-${{ runner.os }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm run check

      - name: Lint & Build
        run: |
          pnpm run lint
          CI=true pnpm run build
