name: wgx-guard

on:
  push:
    paths:
      - ".wgx/**"
      - ".github/workflows/wgx-guard.yml"
      - "pyproject.toml"
      - "Cargo.toml"
  pull_request:
    paths:
      - ".wgx/**"
      - ".github/workflows/wgx-guard.yml"
      - "pyproject.toml"
      - "Cargo.toml"
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: wgx-guard-${{ github.ref }}
  cancel-in-progress: true

jobs:
  guard:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - name: Check .wgx/profile.yml presence
        run: |
          test -f .wgx/profile.yml || { echo "::error::.wgx/profile.yml missing"; exit 1; }
          echo "found .wgx/profile.yml"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install PyYAML
        run: python -m pip install pyyaml
      - name: Validate minimal schema keys
        run: python ci/scripts/validate_wgx_profile.py

      - name: (Optional) UV bootstrap (pyproject present)
        if: ${{ hashFiles('**/pyproject.toml') != '' }}
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          uv --version
          if [ -f uv.lock ]; then uv sync --frozen; else uv sync; fi

      - name: Sync nested Python projects (non-fatal per dir, fail at end if any)
        if: ${{ hashFiles('**/pyproject.toml') != '' }}
        shell: bash
        run: |
          set -euo pipefail
          failures=0
          while IFS= read -r -d '' file; do
            dir="$(dirname "$file")"
            echo "::group::uv sync in $dir"
            rc=0
            if [ -f "$dir/uv.lock" ]; then
              # allow 'set +e' within a subshell to continue on error
              ( set +e; cd "$dir" && uv sync --frozen ); rc=$?
            else
              ( set +e; cd "$dir" && uv sync ); rc=$?
            fi
            if [ $rc -ne 0 ]; then
              echo "::error::uv sync failed in $dir (exit $rc)"
              failures=$((failures+1))
            fi
            echo "::endgroup::"
          done < <(find . -name "pyproject.toml" -print0)
          if [ "$failures" -gt 0 ]; then
            echo "::error::$failures Python workspace(s) failed to sync"
            exit 1
          fi

      - name: Done
        run: echo "wgx-guard passed ✅"
